services:
  - type: web
    name: dr-classifier
    env: python
    pythonVersion: 3.11
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: python dr_inference_app.py
    plan: free
    envVars:
      - key: PORT
        scope: run_and_build
        value: 10000
      - key: GRADIO_SERVER_PORT
        scope: run_and_build
        value: 10000
